---
- name: 'Deploy gcp vm'
  hosts: localhost
  connection: local
  become: false
  gather_facts: no

  vars: 
    gcp_project: "praxis-deck-437908-i4"
    gcp_cred_kind: "serviceaccount"
    gcp_cred_file: "./praxis-deck-437908-i4-b197dfd2933b.json"
    gcp_region: "us-central1"
    gcp_zone: "us-central1-a"
    random_integer: "{{ 1 + (100000 | random) }}"

  # Roles & Tasks
  tasks:

  - name: create a disk
    gcp_compute_disk:
      name: disk-instance
      size_gb: 10
      source_image: projects/debian-cloud/global/images/debian-12-bookworm-v20241009
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk

  - name: create a address
    gcp_compute_address:
      name: address-instance
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: address

  - name: create a instance
    gcp_compute_instance:
      name: "ansible-vm-100{{ random_integer }}"
      project: "{{ gcp_project }}"
      zone: "{{ gcp_zone }}"
      machine_type: e2-micro
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      labels:
        environment: testing
      network_interfaces:
      - network:
          name: "default" # Use the default network
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      auth_kind: serviceaccount
      service_account_file: "{{ gcp_cred_file }}"
      state: present
