---
- name: Main playbook to loop and include task playbook
  hosts: localhost
  gather_facts: no
  vars:
    loop_count: 3  # Change this to the number of iterations you want

  tasks:
    - name: Loop through task playbook multiple times
      include_tasks: task_playbook.yml
      loop: "{{ range(1, loop_count + 1) | list }}"
      loop_control:
        loop_var: iteration
