---
- name: Désinstaller Apache2
  hosts: vms
  become: yes

  tasks:
    - name: Désinstaller Apache2
      apt:
        name: apache2
        state: absent
        purge: yes
        autoremove: yes
        update_cache: yes


